// PURE. The LaunchAgent plist and its wrapper script as text, the `HH:MM` reading, the escaping, the generated files' paths and
// the node-path choice. Return-only: the adapters write the files.
import { InstallRefusal } from './install-refusal.mjs';

/** The one job label (Q-label, recommended A): no personal data in it. */
export const LABEL = 'local.job-alert-harvester.update';
/** The quiet hour chosen against DR-0012 (Sheets write window risk). */
export const DEFAULT_AT = '05:30';

const AT_TEXT = /^([01][0-9]|2[0-3]):([0-5][0-9])$/;

const XML_ENTITIES = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' };
const MESSAGE_LIMIT = 200;
const PLIST_COMMENT = '<!-- Generated by `harvest install`. Remove it with `harvest uninstall`. -->';

/**
 * @param {string} text the value of `--at`
 * @returns {{ hour: number, minute: number } | { refusal: 'install.invalid-time' }} two digits `00`-`23`, a colon, two digits `00`-`59`; anything else is the refusal
 */
export function parseAt(text) {
  const match = AT_TEXT.exec(text);
  return match ? { hour: Number(match[1]), minute: Number(match[2]) } : { refusal: InstallRefusal.INVALID_TIME };
}

/**
 * @param {{ root: string, home: string, nodePath: string, hour: number, minute: number }} spec absolute paths; `root` is the checkout
 * @returns {string} the plist text, marked as generated, every string XML-escaped
 */
export function renderPlist({ root, home, hour, minute }) {
  const paths = pathsFor(root, home);
  const stringEntry = (key, value) => [`  <key>${key}</key>`, `  <string>${xmlEscape(value)}</string>`];
  const integerEntry = (key, value) => [`    <key>${key}</key>`, `    <integer>${value}</integer>`];
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    PLIST_COMMENT,
    '<plist version="1.0">',
    '<dict>',
    ...stringEntry('Label', LABEL),
    '  <key>ProgramArguments</key>',
    '  <array>',
    '    <string>/bin/sh</string>',
    `    <string>${xmlEscape(paths.wrapper)}</string>`,
    '  </array>',
    ...stringEntry('WorkingDirectory', root),
    '  <key>StartCalendarInterval</key>',
    '  <dict>',
    ...integerEntry('Hour', hour),
    ...integerEntry('Minute', minute),
    '  </dict>',
    ...stringEntry('StandardOutPath', paths.outLog),
    ...stringEntry('StandardErrorPath', paths.errLog),
    '</dict>',
    '</plist>',
    '',
  ].join('\n');
}

/**
 * @param {{ root: string, home: string, nodePath: string, hour: number, minute: number }} spec as renderPlist
 * @returns {string} the wrapper script text, every embedded path single-quoted
 */
export function renderWrapper({ root, nodePath }) {
  return `#!/bin/sh
# Generated by harvest install. Remove it with harvest uninstall.
root=${shellQuote(root)}
node=${shellQuote(nodePath)}

notify() {
  command -v osascript >/dev/null 2>&1 || return 0
  osascript -e 'on run argv' -e 'display notification (item 1 of argv) with title "harvest update failed"' -e 'end run' -- "$1" >/dev/null 2>&1 || true
}

cd "$root" || { notify "cannot enter the checkout"; exit 1; }
if [ ! -f "$node" ] || [ ! -x "$node" ]; then
  notify "node is not executable: run harvest install again"
  exit 127
fi

errfile=$(mktemp "\${TMPDIR:-/tmp}/harvest-update.XXXXXX") || { notify "cannot make a temporary file"; exit 1; }
trap 'rm -f "$errfile"' EXIT
trap 'exit 143' HUP INT TERM

"$node" src/cli/harvest.mjs update 2>"$errfile"
status=$?
cat "$errfile" >&2

if [ "$status" -ne 0 ]; then
  line=$(grep -v '^[[:space:]]*$' "$errfile" | tail -n 1 | tr -d '[:cntrl:]' | cut -c1-${MESSAGE_LIMIT})
  notify "\${line:-exit status $status}"
fi
exit "$status"
`;
}

/** @param {string} text @returns {string} `text` as one `sh` word that reads back as exactly `text` */
export function shellQuote(text) {
  return `'${text.replaceAll("'", "'\\''")}'`;
}

/** @param {string} text @returns {string} `text` safe inside an XML text node */
export function xmlEscape(text) {
  return text.replace(/[&<>"']/g, (character) => XML_ENTITIES[character]);
}

/**
 * @param {string} root the checkout
 * @param {string} home the home directory
 * @returns {{ plist: string, wrapper: string, outLog: string, errLog: string }} absolute paths
 */
export function pathsFor(root, home) {
  return {
    plist: `${home}/Library/LaunchAgents/${LABEL}.plist`,
    wrapper: `${root}/.cache/launchd/update.sh`,
    outLog: `${root}/.cache/logs/update.out.log`,
    errLog: `${root}/.cache/logs/update.err.log`,
  };
}

/**
 * @param {{ path: string, realPath: string }[]} candidates the `PATH` entries that hold a `node`, in `PATH` order, with their real paths
 * @param {string} execPath the running binary
 * @returns {string} the first candidate's `path` whose `realPath` equals `execPath`, else `execPath`
 */
export function chooseNodePath(candidates, execPath) {
  const runningBinary = candidates.find((candidate) => candidate.realPath === execPath);
  return runningBinary ? runningBinary.path : execPath;
}
